version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGithubAutomationArtiProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
services:
- serviceName: project.testgithubautomationarti.integrations:gcd_2602
  packages:
  - name: TestGithubAutomationArtiProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2037
